insert into PisoSala (idLocal, piso) values (1, 'S1.1');
insert into PisoSala (idLocal, piso) values (2, 'S1.2');
insert into PisoSala (idLocal, piso) values (3, 'S1.3');
insert into PisoSala (idLocal, piso) values (4, 'S2.1');
insert into PisoSala (idLocal, piso) values (5, 'S2.2');
insert into PisoSala (idLocal, piso) values (6, 'S2.3');
insert into PisoSala (idLocal, piso) values (7, 'S3.1');
insert into PisoSala (idLocal, piso) values (8, 'S3.2');
insert into PisoSala (idLocal, piso) values (9, 'S3.3');
